package com.microsoft.cloudoptimizer.domain.model;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Cost optimization recommendation generated by ML analysis.
 *
 * Recommendations are generated asynchronously during batch processing
 * and cached for low-latency retrieval by the browser extension.
 */
@Entity
@Table(name = "recommendations", indexes = {
    @Index(name = "idx_recommendation_resource", columnList = "provider, resourceId"),
    @Index(name = "idx_recommendation_tenant_status", columnList = "tenantId, status"),
    @Index(name = "idx_recommendation_action", columnList = "action, status")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Recommendation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 64)
    private String tenantId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private CloudProvider provider;

    @Column(nullable = false, length = 512)
    private String resourceId;

    @Column(length = 256)
    private String resourceName;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    private ResourceType resourceType;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    private RecommendationAction action;

    /**
     * Human-readable recommendation summary.
     */
    @Column(nullable = false, length = 1024)
    private String summary;

    /**
     * Detailed explanation of the recommendation.
     */
    @Column(length = 4096)
    private String details;

    /**
     * Current resource configuration (JSON format).
     * Example: {"vcpu": 4, "memoryGb": 16, "sku": "Standard_D4s_v3"}
     */
    @Column(length = 1024)
    private String currentConfig;

    /**
     * Suggested target configuration (JSON format).
     */
    @Column(length = 1024)
    private String suggestedConfig;

    /**
     * Estimated monthly savings in USD.
     */
    @Column(precision = 10, scale = 2)
    private BigDecimal estimatedMonthlySavings;

    /**
     * Estimated percentage savings.
     */
    private Double savingsPercentage;

    /**
     * ML model confidence score (0.0-1.0).
     */
    @Column(nullable = false)
    private Double confidence;

    /**
     * Implementation risk assessment.
     * LOW: Safe, automated
     * MEDIUM: Requires validation
     * HIGH: Potential service impact
     */
    @Column(length = 16)
    private String riskLevel;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private RecommendationStatus status;

    /**
     * When this recommendation was generated.
     */
    @Column(nullable = false)
    private LocalDateTime generatedAt;

    /**
     * When this recommendation expires (needs refresh).
     */
    private LocalDateTime expiresAt;

    /**
     * User who actioned this recommendation.
     */
    @Column(length = 128)
    private String actionedBy;

    /**
     * When the recommendation was actioned.
     */
    private LocalDateTime actionedAt;

    /**
     * User feedback or dismissal reason.
     */
    @Column(length = 512)
    private String feedback;

    @PrePersist
    protected void onCreate() {
        if (generatedAt == null) {
            generatedAt = LocalDateTime.now();
        }
        if (status == null) {
            status = RecommendationStatus.ACTIVE;
        }
        if (expiresAt == null) {
            expiresAt = generatedAt.plusDays(7);
        }
    }
}
